on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo clippy
      - run: cargo fmt -- --check

  test:
    strategy:
      matrix:
        toolchain: ['stable', 'beta', 'nightly']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo run -- cargo.toml
        name: Can hash single file
      - run: cargo run -- target
        name: Can recursively hash directory
      - run: find . -type f | cargo run -- -
        name: Can hash files listed on stdin
